### PR TITLE
Adding srcset URL resolving

### LINKED ISSUE #78: releative srcset urls do not get resolved to absolute urls
[resolveChildUrls()](https://github.com/indieweb/php-mf2/blob/9a5464e0b913ba59f175d87b6950092660f06878/Mf2/Parser.php#L331) takes good care of resolving relative urls in href, src and data attributes. however srcset is left out and image urls in it are left unresolved — which causes problems for indiewebreaders that show broken images if the srcset attribute is used.

### PR DESCRIPTION
**Pull request by voxpelli**
Fixes #78

### CODE REVIEW

**Comment by voxpelli** [comment]
Haven't actually tested the modification to the library, only the transformation function that I took from my example in: https://gist.github.com/voxpelli/6a5dc3c8614ae8937527

So would be great if someone gave this a test before actually merging

**Comment by diplix** [comment]
don’t know about unit tests, but after copy & pasting your Parser.php version in my monocle instance, it works like a charm after refreshing my feeds.

**Comment by voxpelli** [comment]
The failing unit test seems to be unrelated and failing across the board on PHP 5.4

@barnabywalters Would you want unit tests for this addition?

**Comment by voxpelli** [comment]
Ping @gRegorLove @aaronpk as you seems to be the most active here nowadays – any feedback on this PR and whether it's okay as it is or whether I should look into adding a unit test of some kind?

**Comment by gRegorLove** [comment]
@voxpelli I think it's preferred to add a unit test for each new feature. I'll try this PR out soon and let you know. At a glance it looks good.

**Comment by barnabywalters** [comment]
@voxpelli thanks for the PR! It never ceases to amaze me just how complex doing a good job of interpreting and transforming HTML actually is. Which, incidentally, is one of the reasons unit tests are indeed preferred :) Ideally a test should include a srcset with all the valid srcset syntax variations (see [the standard](https://developers.whatwg.org/edits.html#attr-img-srcset), and include both relative and absolute URLs.

**Comment by barnabywalters** [comment]
I wrote a passing unit test for this function based on the WHATWG example srcset, and merged the branch. Many thanks @voxpelli!

**Pull request merged**
