### PR TITLE
Use stdClass when a microformat has no properties

### LINKED ISSUE #171: Properties of empty array not empty object?
https://pin13.net/mf2/?url=https%3A%2F%2Fsingpolyma.net%2F2018%2F04%2Fthoughts-after-ccsummit%2F

I would expect the `h-feed` to have `"properties": {}`

### PR DESCRIPTION
**Pull request by Zegnat**
Fixes #171. Test based on the issue included.

### CODE REVIEW

**Comment by aaronpk** [comment]
Does this match the behavior as described in the readme? https://github.com/indieweb/php-mf2#generating-output-for-json-serialization-with-json-mode See also this issue which looks like the same thing but for `rels` https://github.com/indieweb/php-mf2/issues/29

**Comment by Zegnat** [comment]
> Does this match the behavior as described in the readme?

Yes, I basically copied all the code from the `rels` case, so it makes sure to only overwrite the empty array with `stdClass` when JSON mode is enabled.

**Comment by Zegnat** [comment]
I’ll see if I can extend to test to also test without JSON-mode, so we are sure we aren’t breaking anything…

**Comment by Zegnat** [comment]
Alright, the test now covers both versions of the properties output.

We expect to get a normal (but empty) PHP array back normally so it can be iterated, unless JSON-mode has been turned on in which case we need the ability to serialise to `{}`.

**Pull request merged**
